apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-b00ks.fullname" . }}-config
  labels:
    {{- include "open-b00ks.labels" . | nindent 4 }}
data:
  ENABLE_PUBLIC_REGISTRATION: {{ .Values.config.publicRegistrationEnabled | quote }}
  JWT_TTL_SECONDS: {{ .Values.config.jwtTTLSeconds | quote }}
  REFRESH_TTL_SECONDS: {{ .Values.config.refreshTTLSeconds | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
  TYPESENSE_URL: {{ .Values.config.typesenseURL | quote }}
  {{- with .Values.config.otelServiceName }}
  OTEL_SERVICE_NAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.otelExporterOTLPEndpoint }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.otelExporterOTLPProtocol }}
  OTEL_EXPORTER_OTLP_PROTOCOL: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.otelExporterOTLPInsecure }}
  OTEL_EXPORTER_OTLP_INSECURE: {{ . | quote }}
  {{- end }}
