{{- if and .Values.secrets.create (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-b00ks.secretName" . }}
  labels:
    {{- include "open-b00ks.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseURL | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openAIAPIKey | quote }}
  TYPESENSE_API_KEY: {{ .Values.secrets.typesenseAPIKey | quote }}
{{- end }}
