apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-b00ks.fullname" . }}-web
  labels:
    {{- include "open-b00ks.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
  selector:
    {{- include "open-b00ks.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
